### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by KimJongCode** [cwtools/cwtools#48]
Is the high ram usage normal? Or rather why does CW tools load everything into RAM?
![Unbenannt](https://user-images.githubusercontent.com/94622152/186156334-ec16281f-f0fe-4f46-ad1b-11ba30429f13.PNG)

**Comment by yuto-moriizumi** [comment]
IMO, it is used to provide syntax information.
ex. registered event IDs

**Comment by tboby** [comment]
Vanilla or total conversions for CK3 are really big by number of files, and cwtools has to keep representations of everything in memory yes.

The worst case would be if you did something like a workspace with:

1. Vanilla cached (which is automatic)
2. A total conversion as the mod you're working on (so a copy of every file)
3. Vanilla added to the workspace (some people do this to make it easier to browse)

Similar tools for other programming languages use a lot of memory too:

![image](https://user-images.githubusercontent.com/447391/186158212-a5d9864a-b7dd-471b-9f38-42e3a2c21b3a.png)

Here Rider has a commit of 3.6GB and 2.2GB working set for a smallish C# project.

I spent quite a bit of time working on this and I'm afraid there's not much more I can do!

**Comment by KimJongCode** [comment]
Alright, that's good to know as I need precious RAM lol
